package cn.edu.hit.ir.entity;

import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table menu
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Menu {

    private String id;

    private String parentId; //父亲id

    private String name; //菜单名称

    private String uiName;     //要跳转页面

    private List<Menu> subMenus;  //子菜单列表

    private String icon;

    public Menu(String id, String parentId, String name, String uiName, List<Menu> subMenus, String icon) {
        this.id = id;
        this.parentId = parentId;
        this.name = name;
        this.uiName = uiName;
        this.subMenus = subMenus;
        this.icon = icon;
    }


    public Menu(String id, String parentId, String name, String uiName, String icon) {
        this.id = id;
        this.parentId = parentId;
        this.name = name;
        this.uiName = uiName;
        this.icon = icon;
    }

    public Menu(String id, String parentId, String name, String uiName, List<Menu> subMenus) {
        this.id = id;
        this.parentId = parentId;
        this.name = name;
        this.uiName = uiName;
        this.subMenus = subMenus;
    }

    public Menu(String id, String parentId, String name, String uiName) {
        this.id = id;
        this.parentId = parentId;
        this.name = name;
        this.uiName = uiName;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getParentId() {
        return parentId;
    }

    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUiName() {
        return uiName;
    }

    public void setUiName(String uiName) {
        this.uiName = uiName;
    }

    public List<Menu> getSubMenus() {
        return subMenus;
    }

    public void setSubMenus(List<Menu> subMenus) {
        this.subMenus = subMenus;
    }

    public String getIcon() {
        return icon;
    }

    public void setIcon(String icon) {
        this.icon = icon;
    }

    @Override
    public String toString() {
        return "Menu{" +
                "id='" + id + '\'' +
                ", parentId='" + parentId + '\'' +
                ", name='" + name + '\'' +
                ", uiName='" + uiName + '\'' +
                ", subMenus=" + subMenus +
                '}';
    }
}