package cn.edu.hit.ir.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table robot
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class Robot {
    /**
     * Database Column Remarks:
     *   机器人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   机器人所属用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   机器人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   机器人创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   机器人性别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     * Database Column Remarks:
     *   机器人头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.picture
     *
     * @mbg.generated
     */
    private String picture;

    /**
     * Database Column Remarks:
     *   机器人描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     * Database Column Remarks:
     *   机器人级别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column robot.level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot
     *
     * @mbg.generated
     */

    private String defaultAnswer;

    public Robot(Integer id, String userId, String name, Date createTime, String sex, String picture, String description, Integer level) {
        this.id = id;
        this.userId = userId;
        this.name = name;
        this.createTime = createTime;
        this.sex = sex;
        this.picture = picture;
        this.description = description;
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot
     *
     * @mbg.generated
     */
    public Robot() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot.id
     *
     * @return the value of robot.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot.id
     *
     * @param id the value for robot.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot.user_id
     *
     * @return the value of robot.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot.user_id
     *
     * @param userId the value for robot.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot.name
     *
     * @return the value of robot.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot.name
     *
     * @param name the value for robot.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot.create_time
     *
     * @return the value of robot.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot.create_time
     *
     * @param createTime the value for robot.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot.sex
     *
     * @return the value of robot.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot.sex
     *
     * @param sex the value for robot.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot.picture
     *
     * @return the value of robot.picture
     *
     * @mbg.generated
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot.picture
     *
     * @param picture the value for robot.picture
     *
     * @mbg.generated
     */
    public void setPicture(String picture) {
        this.picture = picture == null ? null : picture.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot.description
     *
     * @return the value of robot.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot.description
     *
     * @param description the value for robot.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column robot.level
     *
     * @return the value of robot.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column robot.level
     *
     * @param level the value for robot.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }


    public String getDefaultAnswer() {
        return defaultAnswer;
    }

    public void setDefaultAnswer(String defaultAnswer) {
        this.defaultAnswer = defaultAnswer;
    }

    @Override
    public String toString() {
        return "Robot{" +
                "id=" + id +
                ", userId='" + userId + '\'' +
                ", name='" + name + '\'' +
                ", createTime=" + createTime +
                ", sex='" + sex + '\'' +
                ", picture='" + picture + '\'' +
                ", description='" + description + '\'' +
                ", level=" + level +
                ", defaultAnswer='" + defaultAnswer + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Robot robot = (Robot) o;

        if (id != null ? !id.equals(robot.id) : robot.id != null) return false;
        if (userId != null ? !userId.equals(robot.userId) : robot.userId != null) return false;
        if (name != null ? !name.equals(robot.name) : robot.name != null) return false;
        if (createTime != null ? !createTime.equals(robot.createTime) : robot.createTime != null) return false;
        if (sex != null ? !sex.equals(robot.sex) : robot.sex != null) return false;
        if (picture != null ? !picture.equals(robot.picture) : robot.picture != null) return false;
        if (description != null ? !description.equals(robot.description) : robot.description != null) return false;
        if (level != null ? !level.equals(robot.level) : robot.level != null) return false;
        return defaultAnswer != null ? defaultAnswer.equals(robot.defaultAnswer) : robot.defaultAnswer == null;
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (userId != null ? userId.hashCode() : 0);
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (createTime != null ? createTime.hashCode() : 0);
        result = 31 * result + (sex != null ? sex.hashCode() : 0);
        result = 31 * result + (picture != null ? picture.hashCode() : 0);
        result = 31 * result + (description != null ? description.hashCode() : 0);
        result = 31 * result + (level != null ? level.hashCode() : 0);
        result = 31 * result + (defaultAnswer != null ? defaultAnswer.hashCode() : 0);
        return result;
    }
}